- package.json
- yarn.lock
https://tools.hmcts.net/jira/browse/RWA-2123
RWA-2123 - Update Dependencies - "config": "3.3.8" "eslint-plugin-import": "2.26.0" "tsconfig-paths": "4.1.1"
```
[ ] Yes
[x] No
```
> RWA-2123 - Update Dependencies

- yarn.lock
**Before creating a pull request make sure that:**
https://tools.hmcts.net/jira/browse/RWA-2190
Fix package vulnerability that causes nightly build to fail
```
[ ] Yes
[X] No
```
> RWA-2190: Fix package vulnerability on nightly build

- Jenkinsfile_CNP
- Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/RWA-2187
afterSuccess Jenkinsfile_CNP and Jenkinsfile_nightly
```
[ ] Yes
[x] No
```
> RWA-2187 - afterSuccess Jenkinsfile_CNP and Jenkinsfile_nightly

- charts/wa-message-cron-service/Chart.yaml
Please remove this line and everything above and fill the following sections:
https://tools.hmcts.net/jira/browse/RWA-2265
Move Charts.job to ~0.7.9
```
[ ] Yes
[ x ] No
```
> RWA-2265 Move Charts.job to ~0.7.9

- charts/wa-message-cron-service/Chart.yaml
- package.json
- yarn.lock
**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
https://tools.hmcts.net/jira/browse/RWA-2361
https://tools.hmcts.net/jira/browse/RWA-2362
Upgrade Typescript to 4.9.5
Bump up glob and types/glob
```
[ ] Yes
[x] No
```
> RWA-2361: Bump glob and types/glob and typescript versions

- package.json
- yarn.lock
https://tools.hmcts.net/jira/browse/RWA-2814
Fix CVE tough-cookie
```
[ x ] Yes
[ ] No
```
> RWA-2814: Fix CVE tough-cookie

- charts/wa-message-cron-service/Chart.yaml
- charts/wa-message-cron-service/values.yaml
https://tools.hmcts.net/jira/browse/RWA-3028
disable active cluster check at service level 
- [ x ] commit messages are meaningful and follow good commit message guidelines
> RWA-3028: disable active cluster check at service level 

- package.json
- yarn.lock
https://tools.hmcts.net/jira/browse/RWA-3202
- [ x] commit messages are meaningful and follow good commit message guidelines
- [ x] README and other documentation has been updated / added (if needed)
- [ x] tests have been updated / new tests has been added (if needed)
- [ x] Does this PR introduce a breaking change
> RWA-3202: Upgrade express.js

- .github/dependabot.yml
- package.json
- yarn.lock
https://tools.hmcts.net/jira/browse/RWA-2447
> RWA-2447: Upgrade Webpack and Delete Dependbot

- package.json
- yarn.lock
https://tools.hmcts.net/jira/browse/RWA-3301
- [x ] commit messages are meaningful and follow good commit message guidelines
- [ x] README and other documentation has been updated / added (if needed)
- [ x] tests have been updated / new tests has been added (if needed)
- [ x] Does this PR introduce a breaking change
> RWA-3301: Update formidable

- .github/renovate.json
https://tools.hmcts.net/jira/browse/RWA-3320
> Allow upgrades to minor or patch only.  Require reviews for Helmet and Chalk

- .github/renovate.json
https://tools.hmcts.net/jira/browse/RWA-3670
- [x ] commit messages are meaningful and follow good commit message guidelines
- [ x] README and other documentation has been updated / added (if needed)
- [ x] tests have been updated / new tests has been added (if needed)
- [ x] Does this PR introduce a breaking change
> RWA-3670: Reconfigure renovate PRs

- charts/wa-message-cron-service/Chart.yaml
https://tools.hmcts.net/jira/browse/RWA-3736
- [ x] commit messages are meaningful and follow good commit message guidelines
- [ x] README and other documentation has been updated / added (if needed)
- [ x] tests have been updated / new tests has been added (if needed)
- [ x] Does this PR introduce a breaking change
> RWA-3736: Upgrade job to 2.1.2

- package.json
- yarn.lock
https://tools.hmcts.net/jira/browse/RWA-3899
update cookie library version
> RWA-3899 - cookie update

- package.json
- yarn.lock
See [RWA-4025](https://tools.hmcts.net/jira/browse/RWA-4025)
> RWA-4025: CVE Fix

- Dockerfile
https://tools.hmcts.net/jira/browse/RWA-4145
Enable corepack as mentioned by platops in thread https://hmcts-reform.slack.com/archives/C8SR5CAMU/p1739887554724709 to unblock pipeline
> RWA-4145: Enable Corepack

- charts/wa-message-cron-service/Chart.yaml
https://tools.hmcts.net/jira/browse/RWA-4155
Update to latest nodejs chart version
> RWA-4155: updating to latest nodejs chart version

- package.json
- yarn.lock
https://tools.hmcts.net/jira/browse/RWA-4194
Upgrading axios to latest
> RWA-4194: Upgrading axios to latest

- SECURITY.md
https://tools.hmcts.net/jira/browse/RWA-4240
**CVE Suppression:** Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?
> RWA-4240: Added Security.md

- README.md
- src/test/routes/home.ts
See [RWA-4006](https://tools.hmcts.net/jira/browse/RWA-4006)
**CVE Suppression:** Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?
> RWA-4006: Test routes fix

- package.json
- yarn.lock
https://tools.hmcts.net/jira/browse/RWA-4525
Upgrading superagent for CVE
Upgrading supertest out of deprecated version
**CVE Suppression:** Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?
> RWA-4525: Upgraded superagent and supertest
